name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
  DISCORD_USERNAME: ${{ secrets.DISCORD_USERNAME }}
  DISCORD_AVATAR: ${{ secrets.DISCORD_AVATAR }}

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Build
      uses: eskatos/gradle-command-action@v1
      with:
        wrapper-directory: gradle
        arguments: compileJava

    - name: Build succeeded
      if: success()
      uses: Ilshidur/action-discord@master
      with:
        args: 'Branch ${GITHUB_REF##*/} build successfully on ${{ matrix.os }}'

    - name: Build failed
      if: failure()
      uses: Ilshidur/action-discord@master
      with:
        args: 'Branch ${GITHUB_REF##*/} build failed on ${{ matrix.os }}'

    - name: Build cancelled
      if: cancelled()
      uses: Ilshidur/action-discord@master
      with:
        args: 'Branch ${GITHUB_REF##*/} build cancelled on ${{ matrix.os }}'
